name: iqhqthailand
favicon: null
layout_spectrum: 0.59213
typography_spectrum: 0.65808
title: English Headquarters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3f5dd'
    - '#333333'
    - '#f1d665'
    - '#ec5b53'
    - '#999999'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
