name: iqhqthailand
favicon: null
layout_spectrum: 0.5893901528324932
typography_spectrum: 0.6366220894269645
title: IQHeadquarters Thailand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3f5dd'
    - '#333333'
    - '#f1d665'
    - '#ec5b53'
    - '#999999'
  brandStrength: 0.275404061190784
  lightness: 0.4681180336046964
  saturation: 0.08339037327095866
  rhythmicContrast: 0.6375535875558853
purpose: []
